### ISSUE TITLE
details of how soft delete works

### ISSUE THREAD

**Issue by jpollard-cs** [iWinston/typeorm-plus#2]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

hi I was just taking a look at the diff here: https://github.com/iWinston/typeorm-plus/compare/iWinston:00d46e...master

curious why you deleted the package.lock file?

also just to verify my understanding - should `softRemove` work with cascades?

**Comment by iWinston** [comment]
Sorry, I deleted this file by accident. And I have added the `package.lock` file again now.

As I refactored this repository so many times, the commit history seems to be a bit messy. 
So I have forked the TypeORM 0.2.19, and recommitting my code now.

I think it's necessary to support cascade on soft-delete.
But I am not sure about which way is better now. There are two ways to specify this behavior:

1. The way behaves like `update`: `cascade:boolean` - if set to true, the related object will be deleted softly in the database.
2. The way behaves like `delete`:  `onSoftDelete: "RESTRICT"|"CASCADE"|"SET NULL"`  - specifies how foreign key should behave when referenced object is deleted softly.

**Comment by jpollard-cs** [comment]
Hmm well I wonder if it's reasonable to assume that *if* you're soft deleting an entity that anywhere you have `delete: { cascade: true }` or equivalent (if you just generally have cascades set to true)  *then* all cascading deletes should be soft deletes. I don't recall - do you have a special soft-deletable model or did you build this into the base model? It might be easier to do this explicitly in terms of generating migrations.

**Comment by iWinston** [comment]
This is the documentation about the `cascade` behavior in TypeORM: [TypeORM](https://typeorm.io/#/relations.)

And I would like to show some examples to explain what the cascading soft deletes may be in TypeORM+.

1. `cascade: boolean`:  It just affects the methods of  `Repository`:  `softRemove` and `recover`

```
const category1 = new Category();
category1.name = "animals";

const category2 = new Category();
category2.name = "zoo";

const question = new Question();
question.categories = [category1, category2];
const newQuestion =  await connection.manager.save(question);

await connection.manager.softRemove(newQuestion);
```
As you can see in this example we did not call save for category1 and category2. They will be automatically soft-deleted because we set `cascade` to true.

2. onSoftDelete: "RESTRICT"|"CASCADE"|"SET NULL": It supports both of `Repository` and `QueryBuilder`

```
await connection.manager.softDelete(Question, 1);
```
if we set `onSoftDelete` to "CASCADE", the categories that belong to this question will be soft-deleted.

I think I will build it into the base model if we consider the cascading soft deletes is a good idea.

**Comment by jpollard-cs** [comment]
I think that looks pretty good to me
if we were to build it into the base model does that necessarily mean that every table generated by the sql generation script will necessarily have a "deletedAt" date?

**Comment by iWinston** [comment]
This feature is a bit complex. I will do some research and experiments before I answer your question.

Could you modify the issue title? Then more people can come to this conversation.

**Comment by iWinston** [comment]
Hi, I have refactored all the code of `TypeORM+`, and supported cascade on soft-delete.

The cascade on soft-delete just affects the methods of Repository: `softRemove` and `recover`
And this is the PR of it:  https://github.com/iWinston/typeorm-plus/pull/8

Now the release 0.0.55  which includes this feature is available.

**Comment by jpollard-cs** [comment]
amazing! I'll take a look when I get some time!
