### ISSUE TITLE
Is it possible to apply multiple where clauses without overring previous one?

### ISSUE THREAD

**Issue by fatihky** [iWinston/typeorm-plus#3]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[*] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

TypeORM's original query builder requires `andWhere` or `orWhere` after the first `where` call. Otherwise it overrides existing `where` condition. The first `where` call can differ depending on the request parameters so it's hard to keep track of the where calls (which one is first, which one is second etc...).

**Comment by iWinston** [comment]
It seems to be an issue of TypeORM rather than TypeORM+.

I think it's very easy to cause bugs, because of the order of the `where` calls.

The simplest way to solve this problem is to use the `andWhere` method only.
It can work fine using `createQueryBuilder('it').andWhere('it.id = 2').andWhere('it.name = "Jack"')`.

Another elegant way is to modify the `where` method and make it behaves like the `andWhere`.  The same behavior of `where` exists in Laravel's ORM: Eloquent.

**Comment by fatihky** [comment]
Yes, that's TypeORM's issue but I thought maybe this was also solved in this fork, among other things. I think I must try using just `andWhere`, thanks.
